In [24]:
grid = [
    [5,3,0,0,7,0,0,0,0],
    [6,0,0,1,9,5,0,0,0],
    [0,9,8,0,0,0,0,6,0],
    [8,0,0,0,6,0,0,0,3],
    [4,0,0,8,0,3,0,0,1],
    [7,0,0,0,2,0,0,0,6],
    [0,6,0,0,0,0,2,8,0],
    [0,0,0,4,1,9,0,0,5],
    [0,0,0,0,8,0,0,7,9]
]

In [25]:
import numpy as np
print(np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [26]:
def possible(y, x, n):
    global grid

    for i in range(0,9):
        # check row
        if grid[y][i] == n:
            return False
        # check column  
        if grid[i][x] == n:
            return False
        
    # check 3x3
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j] == n:
                return False
    return True
    

In [27]:
possible(4,4,3)

False

In [28]:
possible(4,4,5)

True

In [29]:
def solve(more=False):
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y][x] == 0:
                for n in range(1, 10):
                    if possible(y,x,n):
                        grid[y][x] = n
                        solve()
                        grid[y][x] = 0
                return
    print(np.matrix(grid))
    print("Done!")
    
    if not more:
        return
    print(np.matrix(grid))

In [30]:
solve(False)

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
Done!


In [31]:
grid = [
    [5,3,0,0,7,0,0,0,0],
    [6,0,0,1,0,5,0,0,0],
    [0,9,0,0,0,0,0,6,0],
    [8,0,0,0,6,0,0,0,3],
    [4,0,0,8,0,3,0,0,1],
    [7,0,0,0,2,0,0,0,6],
    [0,6,0,0,0,0,2,8,0],
    [0,0,0,4,1,9,0,0,0],
    [0,0,0,0,0,0,0,7,9]
]

In [32]:
solve(True)

[[5 3 4 2 7 6 9 1 8]
 [6 7 8 1 9 5 3 4 2]
 [1 9 2 3 4 8 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 6 8 2 1 7 9]]
Done!
[[5 3 4 2 7 6 9 1 8]
 [6 8 2 1 9 5 3 4 7]
 [1 9 7 3 4 8 5 6 2]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 7 8 4 1 9 6 3 5]
 [3 4 5 6 8 2 1 7 9]]
Done!
[[5 3 4 2 7 6 9 1 8]
 [6 8 7 1 9 5 3 4 2]
 [1 9 2 3 4 8 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 7 8 4 1 9 6 3 5]
 [3 4 5 6 8 2 1 7 9]]
Done!
[[5 3 4 6 7 2 9 1 8]
 [6 7 8 1 9 5 3 4 2]
 [1 9 2 3 4 8 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
Done!
[[5 3 4 6 7 2 9 1 8]
 [6 8 2 1 9 5 3 4 7]
 [1 9 7 3 4 8 5 6 2]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 7 8 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
Done!
[[5 3 4 6 7 2 9 1 8]